name: Update Dependencies

on:
  schedule:
    - cron: "0 8 * * 1"   # weekly Monday
  workflow_dispatch:

jobs:
  update_lean:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v5
      - uses: leanprover-community/lean-update@main
        with:
          on_update_succeeds: pr
          on_update_fails: issue
          update_if_modified: lean-toolchain
